version: '3.8'

services:
  staging-frontend:
    build: ./frontend
    container_name: staging-react
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/staging/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot-staging/conf:/etc/letsencrypt
      - ./certbot-staging/www:/var/www/certbot
    depends_on:
      - staging-backend

  staging-backend:
    build: ./backend
    container_name: staging-node
    ports:
      - "3000:3000"

  certbot-staging:
    image: certbot/certbot
    container_name: certbot-staging
    volumes:
      - ./certbot-staging/conf:/etc/letsencrypt
      - ./certbot-staging/www:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot 
      --email vipin@gmail.com 
      --agree-tos 
      --no-eff-email 
      -d staging.myapp.com
