version: '3.8'

services:
  staging-frontend:
    build: ./frontend
    container_name: staging-react
    ports:
      - "80:80"
    depends_on:
      - staging-backend
    volumes:
      - ./.docker/staging/nginx.conf:/etc/nginx/conf.d/default.conf

  staging-backend:
    build: ./backend
    container_name: staging-node
    ports:
      - "3000:3000"

