version: '3.8'

services:
  prod-frontend:
    build: ./frontend
    container_name: prod-react
    ports:
      - "80:80"
    depends_on:
      - prod-backend
    volumes:
      - ./.docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf

  prod-backend:
    build: ./backend
    container_name: prod-node
    ports:
      - "3000:3000"

