version: '3.8'

services:
  prod-frontend:
    build: ./frontend
    container_name: prod-react
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - prod-backend

  prod-backend:
    build: ./backend
    container_name: prod-node
    ports:
      - "3000:3000"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: > 
      certonly --webroot --webroot-path=/var/www/certbot 
      --email vipin@gmail.com 
      --agree-tos 
      --no-eff-email 
      -d myapp.com
